#!/usr/bin/perl -w

use 5.016;
use strict;

my @week = qw( mon tue wed thu fri sat sun );
 
sub arrayCycle {
  
  my @array = @_;
  
  foreach my $element (@array) {
    
    say $element . "\n";
    
  }
    
}
 
arrayCycle(@week);
