#!/usr/bin/perl -w

use 5.016;
use strict;

# assign list contents separated, and wrapped
# in double quotes to the @week array.
my @week = qw( mon tue wed thu fri sat sun );
 
# user defined functions are called subroutines in perl,
# define a subroutine
sub arrayCycle {
  
  # create a locally scoped array called "array"
  my @array = @_;
  
  
  # '$element' is an instance variable,
  #  the current index of '@array' is assigned to the '$element' variable
  #  each time the block runs.
  foreach my $element (@array) {
    
    # add a newline character to the end of '$element'
    say $element . "\n";
    
  }
    
}
 
arrayCycle(@week);
